export interface Quote {
  text: string
  author: string
}

export const quotes: Quote[] = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Deep work is the superpower of the 21st century.", author: "Cal Newport" },
  { text: "It's not about having time. It's about making time.", author: "Unknown" },
  { text: "One step at a time is all it takes to get you there.", author: "Emily Dickinson" },
  { text: "Productivity is never an accident. It is always the result of commitment to excellence.", author: "Paul J. Meyer" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "Be here now.", author: "Ram Dass" },
  { text: "Slow down and everything you are chasing will come around and catch you.", author: "John De Paola" },
  { text: "You are allowed to be both a masterpiece and a work in progress simultaneously.", author: "Sophia Bush" },
  { text: "In the midst of movement and chaos, keep stillness inside of you.", author: "Deepak Chopra" },
  { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
  { text: "Take rest; a field that has rested gives a bountiful crop.", author: "Ovid" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "She believed she could, so she did.", author: "R.S. Grey" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "What lies within us is far greater than what lies ahead of us or behind us.", author: "Ralph Waldo Emerson" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Small progress is still progress.", author: "Unknown" },
  { text: "The expert in everything was once a beginner.", author: "Helen Hayes" },
  { text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
  { text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { text: "Excellence is not a singular act, but a habit.", author: "Aristotle" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Unknown" },
  { text: "Nothing is impossible. The word itself says 'I'm possible.'", author: "Audrey Hepburn" },
  { text: "The hard days are what make you stronger.", author: "Aly Raisman" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "The secret to productivity is eliminating distractions, not managing time.", author: "Shane Parrish" },
  { text: "You have exactly the same number of hours per day that were given to Helen Keller, Michelangelo, and Leonardo da Vinci.", author: "H. Jackson Brown Jr." },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "Passion is energy. Feel the power that comes from focusing on what excites you.", author: "Oprah Winfrey" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "The distance between who you are and who you want to be is what you do.", author: "Unknown" },
  { text: "You've got this.", author: "Unknown" },
  { text: "Breathe. You're going to be okay. Breathe and remember that you've been in this place before.", author: "Daniell Koepke" },
]
